// ASIAXT4ARJIMNC7PZGTL
// HQQbdGYvYKXjoMWyxvmqXrDQ6BzNaR9zBikMtdtf
// us-east-1
// Error: AuthFailure: AWS was not able to validate the provided access credentials
//     at Request.extractError (/var/task/node_modules/aws-sdk/lib/services/ec2.js:50:35)
//     at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
//     at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
//     at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)
//     at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
//     at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
//     at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
//     at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
//     at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:688:12)
//     at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {
//   code: 'AuthFailure',
//   time: 2024-02-28T07:55:49.452Z,
//   requestId: '7517afc9-077c-4110-9426-c2bcff6fb228',
//   statusCode: 401,
//   retryable: false,
//   retryDelay: 37.939087486271795
// }


